// Code generated by protoc-gen-go. DO NOT EDIT.
// source: probes/malloc/malloc.proto

/*
Package malloc is a generated protocol buffer package.

It is generated from these files:
	probes/malloc/malloc.proto

It has these top-level messages:
	MallocEntry
*/
package malloc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MallocEntry struct {
	Type        string `protobuf:"bytes,1,opt,name=Type" json:"Type,omitempty"`
	PID         int64  `protobuf:"varint,2,opt,name=PID" json:"PID,omitempty"`
	ProcessName string `protobuf:"bytes,3,opt,name=ProcessName" json:"ProcessName,omitempty"`
	Bytes       int64  `protobuf:"varint,4,opt,name=Bytes" json:"Bytes,omitempty"`
	Timestamp   int64  `protobuf:"varint,5,opt,name=Timestamp" json:"Timestamp,omitempty"`
}

func (m *MallocEntry) Reset()                    { *m = MallocEntry{} }
func (m *MallocEntry) String() string            { return proto.CompactTextString(m) }
func (*MallocEntry) ProtoMessage()               {}
func (*MallocEntry) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *MallocEntry) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *MallocEntry) GetPID() int64 {
	if m != nil {
		return m.PID
	}
	return 0
}

func (m *MallocEntry) GetProcessName() string {
	if m != nil {
		return m.ProcessName
	}
	return ""
}

func (m *MallocEntry) GetBytes() int64 {
	if m != nil {
		return m.Bytes
	}
	return 0
}

func (m *MallocEntry) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func init() {
	proto.RegisterType((*MallocEntry)(nil), "malloc.MallocEntry")
}

func init() { proto.RegisterFile("probes/malloc/malloc.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 155 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2a, 0x28, 0xca, 0x4f,
	0x4a, 0x2d, 0xd6, 0xcf, 0x4d, 0xcc, 0xc9, 0xc9, 0x4f, 0x86, 0x52, 0x7a, 0x05, 0x45, 0xf9, 0x25,
	0xf9, 0x42, 0x6c, 0x10, 0x9e, 0x52, 0x27, 0x23, 0x17, 0xb7, 0x2f, 0x98, 0xe9, 0x9a, 0x57, 0x52,
	0x54, 0x29, 0x24, 0xc4, 0xc5, 0x12, 0x52, 0x59, 0x90, 0x2a, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x19,
	0x04, 0x66, 0x0b, 0x09, 0x70, 0x31, 0x07, 0x78, 0xba, 0x48, 0x30, 0x29, 0x30, 0x6a, 0x30, 0x07,
	0x81, 0x98, 0x42, 0x0a, 0x5c, 0xdc, 0x01, 0x45, 0xf9, 0xc9, 0xa9, 0xc5, 0xc5, 0x7e, 0x89, 0xb9,
	0xa9, 0x12, 0xcc, 0x60, 0xc5, 0xc8, 0x42, 0x42, 0x22, 0x5c, 0xac, 0x4e, 0x95, 0x25, 0xa9, 0xc5,
	0x12, 0x2c, 0x60, 0x5d, 0x10, 0x8e, 0x90, 0x0c, 0x17, 0x67, 0x48, 0x66, 0x6e, 0x6a, 0x71, 0x49,
	0x62, 0x6e, 0x81, 0x04, 0x2b, 0x58, 0x06, 0x21, 0x90, 0xc4, 0x06, 0x76, 0x9a, 0x31, 0x20, 0x00,
	0x00, 0xff, 0xff, 0x27, 0x8c, 0x64, 0x7e, 0xb8, 0x00, 0x00, 0x00,
}
